# Laptop Price

In [62]:
import numpy as np
import pandas as pd
import seaborn as sns

In [63]:
df = pd.read_csv('laptop_price.csv', encoding='latin-1')

In [64]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

In [52]:
df['laptop_ID'] = df['laptop_ID'].astype('int16')

In [43]:
screenResolution = df['ScreenResolution'].str.split('\s').str[-1].str.lower().str.split('x', expand=True)
df['X_res'] = screenResolution[0].astype('int16')
df['Y_res'] = screenResolution[1].astype('int16')

In [44]:
df['Ram'] = df['Ram'].str.strip().str.replace('GB', '').astype('int16')

In [45]:
# df['Weight'] = df['Weight'].str.strip().str.replace('kg', '') # one way
df['Weight'] = df['Weight'].str.strip().str.split('(\d+|\d+\.\d+)([KkMm]g)', expand=True)[1].astype('float32') # another way

In [46]:
df['GpuBrand'] = df['Gpu'].str.strip().str.split('\s').str[0].astype('str')

In [47]:
df['CpuClockSpeed'] = df['Cpu'].str.strip().str.split('(\d+|\d+\.\d|\.\d)GHz').str[1].astype('float32')

In [48]:
df = df.drop(['ScreenResolution', 'Gpu', 'Cpu'], axis=1)

In [259]:
memory = df['Memory'].str.split('\+', expand=True)

In [260]:
layer1 = memory[0].str.extract('(\d+)([^\d+]+)', expand=True)

In [262]:
layer1[0] = layer1[0].astype('int32')

In [263]:
layer1.loc[layer1[1].str.contains('TB'), 0] *= 1024

In [272]:
layer1[0]

0        128
1        128
2        256
3        512
4        256
        ...
1298     128
1299     512
1300      64
1301    1024
1302     500
Name: 0, Length: 1303, dtype: int32

In [249]:
df.dtypes

laptop_ID             int64
Company              object
Product              object
TypeName             object
Inches              float64
ScreenResolution     object
Cpu                  object
Ram                  object
Memory               object
Gpu                  object
OpSys                object
Weight               object
Price_euros         float64
dtype: object

In [50]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Ram,Memory,OpSys,Weight,Price_euros,X_res,Y_res,GpuBrand,CpuClockSpeed
0,1,Apple,MacBook Pro,Ultrabook,13.3,8,128GB SSD,macOS,1.37,1339.69,2560,1600,Intel,2.3
1,2,Apple,Macbook Air,Ultrabook,13.3,8,128GB Flash Storage,macOS,1.34,898.94,1440,900,Intel,1.8
2,3,HP,250 G6,Notebook,15.6,8,256GB SSD,No OS,1.86,575.00,1920,1080,Intel,2.5
3,4,Apple,MacBook Pro,Ultrabook,15.4,16,512GB SSD,macOS,1.83,2537.45,2880,1800,AMD,2.7
4,5,Apple,MacBook Pro,Ultrabook,13.3,8,256GB SSD,macOS,1.37,1803.60,2560,1600,Intel,3.1